### ISSUE TITLE
generate_anser.sh运行报错。

### ISSUE THREAD

**Issue by wangzaistone** [FreedomIntelligence/CMB#10]
我运行generate_anser.sh时会报错，环境为有4张A100(40G)的卡，模型是baichuan2-13b，这个大小的模型下在其他项目中4张A100不会报错。请问是哪个地方配置出问题了？多谢
报错信息为： 
`Traceback (most recent call last):
  File "/home/LLM/tutorials/CMB/./src/generate_answers.py", line 205, in <module>
    main(args)
  File "/home/LLM/tutorials/CMB/./src/generate_answers.py", line 41, in main
    runner = runner_class.from_config(
  File "/home/LLM/tutorials/CMB/src/../workers/base.py", line 66, in from_config
    return cls(
  File "<string>", line 11, in __init__
  File "/home/LLM/tutorials/CMB/src/../workers/base.py", line 46, in __post_init__
    self.wrap_model()
  File "/home/LLM/tutorials/CMB/src/../workers/base.py", line 152, in wrap_model
    self.model = self.accelerator.prepare(self.model)
  File "/home/anaconda/envs/zhixi/lib/python3.9/site-packages/accelerate/accelerator.py", line 1284, in prepare
    result = tuple(
  File "/home/anaconda/envs/zhixi/lib/python3.9/site-packages/accelerate/accelerator.py", line 1285, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/anaconda/envs/zhixi/lib/python3.9/site-packages/accelerate/accelerator.py", line 1090, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/home/anaconda/envs/zhixi/lib/python3.9/site-packages/accelerate/accelerator.py", line 1383, in prepare_model
    model = model.to(self.device)
  File "/home/anaconda/envs/zhixi/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2053, in to
    return super().to(*args, **kwargs)
  File "/home/anaconda/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/anaconda/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/anaconda/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/anaconda/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/anaconda/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/anaconda/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 150.00 MiB (GPU 3; 39.41 GiB total capacity; 626.00 MiB already allocated; 103.56 MiB free; 626.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):`

generate_anser.sh 的配置代码为： 

> `
”“” 
input_path='./data/CMB-Exam/CMB-test/CMB-test-choice-question-merge.json'   # CMB-Exam
task_name='Exam' 
model_id="baichuan-13b-chat" # which model to evaluate
mkdir -p logs/${task_name}/
accelerate launch --gpu_ids='all' --main_process_port 27274 --config_file ./configs/accelerate_config.yaml  ./src/generate_answers.py \
--use_cot \
--model_id=$model_id \
--all_gather_freq=20 \
--input_path=$input_path \
--output_path=./result/${task_name}/${model_id}/modelans.json \
--batch_size 1 \
--model_config_path="./configs/model_config.yaml" 
“”“
`

**Comment by wangxidong06** [comment]
Can you show me the "./configs/accelerate_config.yaml"

**Comment by wangzaistone** [comment]
> Can you show me the "./configs/accelerate_config.yaml"
Thanks for your reply and help ! , content in "./configs/accelerate_config.yaml" are as follows , 

compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: '4,5,6,7'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 4  # number of GPUs
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

**Comment by wangzaistone** [comment]
> Can you show me the "./configs/accelerate_config.yaml"
Thanks for your reply and help ! , content in "./configs/accelerate_config.yaml" are as follows , 

compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: '4,5,6,7'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 4  # number of GPUs
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

**Comment by wangxidong06** [comment]
您可以参考 https://github.com/wangxidong06/LLMSFT_template/blob/main/accelerate-zero/configs/finetune.yaml 上述deepspeed config后的配置需要tab递进

**Comment by wangzaistone** [comment]
> 您可以参考 https://github.com/wangxidong06/LLMSFT_template/blob/main/accelerate-zero/configs/finetune.yaml 上述deepspeed config后的配置需要tab递进
在配置的时候 “加Deepspeed Zero优化显存(Zero1/Zero2/Zero3)” ，参照您给的格式和专门的提醒tab(感谢） ，
按如下配置：
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_clipping: 1.0(都有tab空格）
  offload_optimizer_device: cpu(都有tab空格）
  offload_param_device: none(都有tab空格）
  zero3_init_flag: true(都有tab空格）
  zero3_save_16bit_model: false(都有tab空格）
  zero_stage: 3(都有tab空格）
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: '6,7'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2 # number of GPUs
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: true   

会报错，报错如下： 
>torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 136.00 MiB (GPU 1; 39.41 GiB total capacity; 10.22 GiB already allocated; 43.56 MiB free; 10.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF


如果只是将上面 distributed_type: 的值由 MULTI_GPU 改为 DEEPSPEED会报错，报错同如下参照上面的链接“ https://github.com/wangxidong06/LLMSFT_template/blob/main/accelerate-zero/configs/finetune.yaml 上述deepspeed config后的配置” 后，更改 num_machines: 1 和 num_processes: 2 后，两者的报错一样，
配置如下:
>compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: false
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'yes'
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false  


报错如下：
>
“ File "/home/LLM/tutorials/CMB/./src/generate_answers.py", line 205, in <module>
    main(args)
  File "/home/LLM/tutorials/CMB/./src/generate_answers.py", line 41, in main
    runner = runner_class.from_config(
  File "/home/LLM/tutorials/CMB/workers/base.py", line 66, in from_config
    return cls(
  File "<string>", line 11, in __init__
  File "/home/LLM/tutorials/CMB/workers/base.py", line 46, in __post_init__
    self.wrap_model()
  File "/home/LLM/tutorials/CMB/workers/base.py", line 152, in wrap_model
    self.model = self.accelerator.prepare(self.model)
  File "/home/anaconda/envs/zhixi/lib/python3.9/site-packages/accelerate/accelerator.py", line 1280, in prepare
    result = self._prepare_deepspeed(*args)
  File "/home/anaconda/envs/zhixi/lib/python3.9/site-packages/accelerate/accelerator.py", line 1515, in _prepare_deepspeed
    raise ValueError(
ValueError: When using DeepSpeed `accelerate.prepare()` requires you to pass at least one of training or evaluation dataloaders or alternatively set an integer value in `train_micro_batch_size_per_gpu` in the deepspeed config fileor assign integer value to `AcceleratorState().deepspeed_plugin.deepspeed_config['train_micro_batch_size_per_gpu']`.”


请问如果在2张A100或者4张A100上运行您generate_answers.sh  这个评测代码，我该如何配置 accelerate_config.yaml？

**Comment by wangzaistone** [comment]
And  I found the similiar problem  ,like this issue ,[here ](https://github.com/FreedomIntelligence/CMB/issues/4), it seems not only me follow the default code and param  set , it don't works too

**Comment by PuppyKnightUniversity** [comment]
hey, I met this problem and fixed it by adding a config ""device_map": "auto" in your model's worker, meanwhile change the "num_processes: 1" of your accelerate config. Then it works.

**Comment by wangzaistone** [comment]
> hey, I met this problem and fixed it by adding a config ""device_map": "auto" in your model's worker, meanwhile change the "num_processes: 1" of your accelerate config. Then it works.

thanks a lot for your help!

**Comment by wangzaistone** [comment]
> hey, I met this problem and fixed it by adding a config ""device_map": "auto" in your model's worker, meanwhile change the "num_processes: 1" of your accelerate config. Then it works.

人大的校友吗？

**Comment by g-h-chen** [comment]
We will close the issue for now as the problem is seemingly solved.
