### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory运行报错

### ISSUE THREAD

**Issue by WangRongsheng** [FreedomIntelligence/CMB#4]
```python
基础环境：4 X NVIDIA A100 (40GB) ，accelerate==0.21.0

accelerate配置：
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: '0,1,2,3'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

报错：
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.71 GiB (GPU 0; 39.41 GiB total capacity; 24.74 GiB already allocated; 13.17 GiB free; 24.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONFERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 156578) of binary: /root/anaconda3/envs/cmb/bin/python
```

**Comment by g-h-chen** [comment]
@WangRongsheng Hi Rongsheng, you may want to decrease your batch size, which can be configured [here](https://github.com/FreedomIntelligence/CMB/blob/840e8fc8bf2368c693f1ee720a98269bdaf789b0/generate_answers.sh#L17C1-L17C1). 40G should be far from enough even for a 13B model using batch size 1.

**Comment by WangRongsheng** [comment]
I think there might be some errors here. The 13B model can be trained on a 4 X A100 (40GB). If I set `batch_size=1`, which parameters can I adjust to ensure smooth inference? Thank you.

**Comment by g-h-chen** [comment]
> I think there might be some errors here. The 13B model can be trained on a 4 X A100 (40GB). If I set `batch_size=1`, which parameters can I adjust to ensure smooth inference? Thank you.

@WangRongsheng What do you mean by "ensuring a smooth inference"? Setting `batch_size=1` should solve your OOM problem here. If you want to have a faster inference speed, consider using a larger batch size and passing `do_sample=False` [here](https://github.com/FreedomIntelligence/CMB/blob/840e8fc8bf2368c693f1ee720a98269bdaf789b0/configs/model_config.yaml#L11).

**Comment by WangRongsheng** [comment]
I will try it! Thank you!

**Comment by wangzaistone** [comment]
> I will try it! Thank you!

Did you have solved the problem ? I meet the same problem too ,it not works as your list in 4*A100(40G),how you did it ?

**Comment by PuppyKnightUniversity** [comment]
hey, I met this problem and fixed it by adding a config ""device_map": "auto" in your model's worker, meanwhile change the "num_processes: 1" of your accelerate config. Then it works.

**Comment by BestLemoon** [comment]
> hey, I met this problem and fixed it by adding a config ""device_map": "auto" in your model's worker, meanwhile change the "num_processes: 1" of your accelerate config. Then it works.

hey there, I want to confirm where to add the config `device_map`, is it in `hf_model_config`? by the way, the `num_processes:1` seems conflict with `MULTI_GPU`.
Thank you

**Comment by ATP-BME** [comment]
This code seems to be taking up more memory than expected while inferencing. I used the llama2-7b to inference and got an OOM error on a 3090 GPU

compute_environment: LOCAL_MACHINE
distributed_type: NO # MULTI_GPU # NO
downcast_bf16: 'no'
gpu_ids: '0'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1  # number of GPUs
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

and

batch_size=1
